In [6]:
from  numpy import *

In [10]:
a = numpy.array([101,102,103,104,105])
b = numpy.array([101,102,103,104,105],int)
c = numpy.array([101.1,102.2,103.3,104.4,105.5],float)
d = numpy.array(['Abhi','Prithvi','Sandesh','Ram'])
print(a)
print(b)
print(c)
print(d)


[101 102 103 104 105]
[101 102 103 104 105]
[101.1 102.2 103.3 104.4 105.5]
['Abhi' 'Prithvi' 'Sandesh' 'Ram']


In [11]:
a = numpy.array([101,102,103,104,105])
for element in a:
    print(element,end="")

101102103104105

In [12]:
n = len(a)
for i in range(n):
    print(a[i],end=" ")


101 102 103 104 105 

In [13]:
# 2.Linspace()
# numpy.linspace(start,stop,num=50)
from numpy import *

In [9]:
a = linspace(1,8)
print(a)

[1.         1.14285714 1.28571429 1.42857143 1.57142857 1.71428571
 1.85714286 2.         2.14285714 2.28571429 2.42857143 2.57142857
 2.71428571 2.85714286 3.         3.14285714 3.28571429 3.42857143
 3.57142857 3.71428571 3.85714286 4.         4.14285714 4.28571429
 4.42857143 4.57142857 4.71428571 4.85714286 5.         5.14285714
 5.28571429 5.42857143 5.57142857 5.71428571 5.85714286 6.
 6.14285714 6.28571429 6.42857143 6.57142857 6.71428571 6.85714286
 7.         7.14285714 7.28571429 7.42857143 7.57142857 7.71428571
 7.85714286 8.        ]


In [14]:
a = linspace(1,8,6)
print(a)

[1.  2.4 3.8 5.2 6.6 8. ]


In [15]:
# 3.logspace
# logspace(start,stop,num=50,base=10)
a = logspace(1,3,5)
print(a)

[  10.           31.6227766   100.          316.22776602 1000.        ]


In [16]:
# Mathematical
a = a = numpy.array([101,102,103,104,105])
a = a-5
for i in a:
    print(i,end=" ")

96 97 98 99 100 

In [17]:
a = array([101,102,103,104,105])
b = array([101,102,103,104,105])
r = a+b
print(r)

[202 204 206 208 210]


In [20]:
a = array([101,102,103,104,105])
b = array([10,20,30,40,50])
# where()
c = where(a>b,a,b)
print(c)

[101 102 103 104 105]


In [19]:
# 4. nonzero()
a = array([101,0,103,104,105])
r = nonzero(a)
print(r)

(array([0, 1, 2, 3, 4]),)


In [21]:
#  view
a = array([101,0,103,104,105])
b = a.view()
a[1] = 80
b[2] = 300
print('a = ',a)
print('b = ',b)
print('Location of a = ',id(a))
print('Location of b = ',id(b))
      

a =  [101  80 300 104 105]
b =  [101  80 300 104 105]
Location of a =  2072912796560
Location of b =  2073296380688


In [23]:
a = array([101,200,103,104,105])
b = copy(a)
a[1] = 80
b[2] = 300
print('a = ',a)
print('b = ',b)

a =  [101  80 103 104 105]
b =  [101 200 300 104 105]


In [26]:
# user input
n = int(input("Enter array Size"))
a = zeros(n,dtype = int)
for i in range(len(a)):
    x = int(input("Enetr element"))
    a[i] = x
print(a)

Enter array Size 3
Enetr element 1
Enetr element 2
Enetr element 3


[1 2 3]


In [27]:
# two D
a = array([[10,20,30,40],[50,60,70,80]])
print(a)

[[10 20 30 40]
 [50 60 70 80]]


In [28]:
for r in a:
    for c in r:
        print(c,end=" ")
    print()

10 20 30 40 
50 60 70 80 


In [29]:
a = zeros((3,2))
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [30]:
# reshape
a = array([1,2,3,4,5,6])
b = reshape(a,(2,3))
print(a)
print(b)


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [31]:
# flatten()
a = array([[1,2,3],[4,5,6]])
b = a.flatten()
print(a)
print(b)



[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [34]:
# 2d user input
m = int(input("Enter no. of  row"))
n = int(input("Enter no. of  column"))
a = zeros((m,n),dtype = int)
u = len(a)
for i in range(u):
    for j in range(len(a[i])):
        x = int(input("Enter element"))
        a[i][j]=x
for i in range(u):
    for j in range(len(a[i])):
        print(a[i][j],end=" ")




Enter no. of  row 2
Enter no. of  column 2
Enter element 1
Enter element 2
Enter element 8
Enter element 9


1
2
8
9


In [36]:
print(a[1:])

[[8 9]]


In [37]:
print(a.shape)

(2, 2)


In [38]:
print(a.ndim)

2


In [39]:
print(a.size)

4


In [41]:
print(a.itemsize)

8


In [42]:
print(type(a))

<class 'numpy.ndarray'>
